### ISSUE TITLE
even_odd_site.py issue

### ISSUE THREAD

**Issue by cierrajenn** [hsharman/harry#8]
Should check if i is an even number, and produce a corresponding table format.
Instead checks if i / 2 == 0, which is only true if i is 0, which never happens.
To resolve this issue, switch i / 2 == 0 to i % 2 == 0.
This bug is relatively critical, as it will always produce the unwanted/incorrect table format. The bug will be encountered every time the for loop iterates, so 50 times.
This is a medium impact issue as it won't ruin anything, but will compromise the intended output of the table.

**Comment by wyattchrisman** [comment]
Fixed Bugs
